# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graduator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20, null=True)),
                ('LastName', models.CharField(max_length=20, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('adress', models.CharField(max_length=30, null=True)),
                ('HighestEducation', models.CharField(max_length=30, null=True)),
                ('Employed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100, null=True)),
                ('projectDescription', models.TextField(max_length=200, null=True)),
                ('projectScreenshot', models.CharField(max_length=200, null=True)),
                ('projectlink', models.CharField(max_length=200, null=True)),
                ('certificationImage', models.CharField(max_length=200, null=True)),
                ('graduator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduators.graduator')),
            ],
        ),
    ]
