# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduators', '0002_graduator_graduationyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduator',
            name='FirstName',
        ),
        migrations.AddField(
            model_name='graduator',
            name='FullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
