# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduators', '0003_auto_20170521_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduator',
            name='FullName',
        ),
        migrations.AddField(
            model_name='graduator',
            name='FirstName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
