# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduators', '0004_auto_20170521_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduator',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='graduator',
            name='LastName',
        ),
    ]
