# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduators', '0005_auto_20170521_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='internshipExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=100, null=True)),
                ('Position', models.CharField(max_length=100, null=True)),
                ('Roles', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='graduator',
            name='image',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='internshipexperience',
            name='graduator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduators.graduator'),
        ),
    ]
