# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduators', '0006_auto_20170623_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipexperience',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='internshipexperience',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='internshipexperience',
            old_name='Roles',
            new_name='roles',
        ),
    ]
